68 design proposals low effort
curacultura/curacultura-website pull request #70
Opened 2024-01-25 10:12 UTC by juanjoseortega-aircury

2024-01-25 10:56 UTC, cristobaldiaz-aircury requested changes
Just pending to ask the client if they are happy with the font you chose. Maybe even providing them with different proposals would be nice.

The rest looks good.

2024-02-01 14:50 UTC, cristobaldiaz-aircury requested changes
1. There are many scss variables that after the changes aren't used anymore. As it seems like there are many of them, create a ticket to solve the problem.
2. Look for a way to use the fonts without adding them to the repository. It can be done as a separate ticket.

2024-02-01 14:50 UTC, cristobaldiaz-aircury commented on assets/js/img_clicker.js
> +        document.get
I'm guessing you left this by accident

2024-02-02 07:07 UTC, juanjoseortega-aircury commented
> 1. There are many scss variables that after the changes aren't used anymore. As it seems like there are many of them, create a ticket to solve the problem.
> 2. Look for a way to use the fonts without adding them to the repository. It can be done as a separate ticket.

The variables can be deleted at the ticket for cleaning unused code.
About the fonts, only Julius Sans can be used from google fonts but this downgrade the performance

2024-02-02 09:43 UTC, cristobaldiaz-aircury approved these changes

2024-02-02 09:43 UTC, merged