#82 spanish translation of index, archive, contact, manifiesto, offering, projects and work
curacultura/curacultura-website pull request #91
Opened 2024-04-29 09:48 UTC by albertofountain-aircury

2024-04-29 11:11 UTC, cristobaldiaz-aircury requested changes

2024-04-29 11:11 UTC, cristobaldiaz-aircury commented on es/index.md
> +# publish date (used for seo)
Remove commented code

2024-04-29 11:11 UTC, cristobaldiaz-aircury commented on es/tabs/archive.md
> +---
Any reason to have this file?

2024-04-29 11:34 UTC, juanjoseortega-aircury reviewed
Typo error's from client document

2024-04-29 11:34 UTC, juanjoseortega-aircury commented on _data/content/projects/es.yml
> +        la oferta pública de la Mainel que se centra en la mejora de la
"la oferta publica de la Mainel" sounds weird, maybe remove "la" before "Mainel"

2024-04-29 11:34 UTC, juanjoseortega-aircury commented on _data/content/projects/es.yml
> +        comparten los curadores y las instituciones mismos. Tanto los
"las instituciones mismos" it's wrong, it should be "mismas"

2024-04-29 11:34 UTC, juanjoseortega-aircury commented on _data/content/projects/es.yml
> +        décadas de los 1960 hasta los 1990, con algunas piezas también
In English translation we have 1960 to 1980, and here in Spanish we have it from 1960 to 1990. maybe this should be asked to the client

2024-04-29 11:34 UTC, juanjoseortega-aircury commented on _data/content/projects/es.yml
> +        de derechos, la memoria y las lucha por la paz y la autonomía. En
"las lucha" should be at singular, so should be "la"

2024-04-29 11:34 UTC, juanjoseortega-aircury commented on es/index.md
> +       <p>"Curar es cuidar”. Cuidar la cultura significa cuidar a las personas. Esta filosofía nos guía tanto en los proyectos que creamos o los que aceptamos, como también en nuestro comportamiento
"como cuidar" should have accent at "como"

2024-04-29 11:34 UTC, juanjoseortega-aircury commented on es/tabs/manifiesto.md
> +          habitan, ya sean inquilinos permanentes o visitantes poco frecuentes, trabajadores y
"inquilinos" here sounds weird for me, maybe this should be reviewed or asked to the client

2024-04-29 11:34 UTC, cristobaldiaz-aircury commented on es/tabs/archive.md
> +---
If we're not using it in English it should be removed then.

2024-04-29 11:49 UTC, juanjoseortega-aircury commented on _data/lang/es.yml
>  image_viewer:
At line 51 `some_rights_reserved` should me modified to Spanish translation

2024-04-29 11:54 UTC, juanjoseortega-aircury commented on es/tabs/offering.md
> +                            <li>inglés</li>
Languages should be at uppercase

2024-04-30 09:00 UTC, cristobaldiaz-aircury requested changes

2024-04-30 09:00 UTC, cristobaldiaz-aircury commented on es/tabs/work.md
> +                Londres. (todo el Reino Unido).
Remove the stop in `Universidad de Londres. (todo el Reino Unido).`. It should look like this:
``Universidad de Londres (todo el Reino Unido).``

2024-04-30 09:00 UTC, cristobaldiaz-aircury commented on _data/content/projects/es.yml
> +        ejecutándose anualmente. Partiendo de una exploración de las
Maybe `realizándose` instead of `ejecutándose`? Ask client

2024-04-30 10:22 UTC, cristobaldiaz-aircury approved these changes

2024-04-30 10:22 UTC, merged