#92 Changed various proposals from the client
curacultura/curacultura-website pull request #93
Opened 2024-05-02 09:30 UTC by albertofountain-aircury

2024-05-02 10:15 UTC, juanjoseortega-aircury requested changes

2024-05-02 10:15 UTC, juanjoseortega-aircury commented on _data/content/projects/es.yml
> +      project_excerpt: "Módulo para el máster 'Mercado Global del Arte'"
Ask about this change to the client

2024-05-02 10:15 UTC, juanjoseortega-aircury commented on _data/content/projects/en.yml
> +        Both the topics of this discussion and the motivations behind the Mainel’s programming show a profound care for the public, whose lives both seek to enrich and empower. See <a href="https://m
Add a br here as Spanish version (if you change the zoom or you have a different resolution it will see different as Spanish)

2024-05-02 10:15 UTC, juanjoseortega-aircury commented on es/tabs/work.md
> +            museos de Europa y Medio Oriente desde 2010. También orienta a
Ask about this change to the client

2024-05-07 06:40 UTC, cristobaldiaz-aircury approved these changes

2024-05-07 06:42 UTC, merged